spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/pawn?createDatabaseIfNotExist=true
    username: root
    password: Anhkiet_2004
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create # or create, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 8080