name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.head_branch == 'anhkiet-branch' }}
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:latest

      - name: Delete old container if existed
        run: sudo docker rm -f ${{secrets.DOCKER_CONTAINER_NAME}} || true

      - name: Run Docker container
        run: sudo docker run -d -p ${{secrets.SERVER_PORT}}:${{secrets.SERVER_PORT}} --name ${{secrets.DOCKER_CONTAINER_NAME}} ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}
