name: CD Pipeline

on:
  push:
    branches:
      - anhkiet-branch

jobs:
  debug:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Triggered by ${{ github.event.workflow_run.head_branch }}"
  deploy:
    timeout-minutes: 5
    runs-on: self-hosted

    steps:
      - name: Start deploy
        run: echo "🚀 Start deploy..."

      - name: Who am i?
        run: who

      - name: Pull Docker image
        run: sudo docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}:latest

      - name: Delete old container if existed
        run: sudo docker rm -f ${{secrets.DOCKER_CONTAINER_NAME}} || true

      - name: Run Docker container
        run: | 
          sudo docker run -d -p ${{secrets.SERVER_PORT}}:${{secrets.SERVER_PORT}} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            --name ${{secrets.DOCKER_CONTAINER_NAME}} ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGE_NAME}}

      - name: Finished
        run: echo "✅ Finished Deploy"